### ISSUE TITLE
Mac Support?

### ISSUE THREAD

**Issue by joemccann** [pyth-network/pyth-client#2]
Would love to take this for a spin on Mac.

**Comment by joemccann** [comment]
![image](https://user-images.githubusercontent.com/48234/118293736-d19cc500-b48e-11eb-81d1-eedc1db7dc90.png)

**Comment by joemccann** [comment]
Does this only work on platforms that support `epoll` or is there going to be x-platform support?

**Comment by evan-gray** [comment]
This repo is intended primarily for data providers. For consumers, we have made [Rust](https://github.com/pyth-network/pyth-client-rs) and [JavaScript](https://github.com/pyth-network/pyth-client-js) libraries available. We may consider adding Mac support in the future, but since we don't have any immediate plans I'll close this. Feel free to reach out on our [discord](https://discord.gg/Ff2XDydUhu) if you have questions.

**Comment by joemccann** [comment]
Great thanks. You can close.
